spring.application.name=recipe-search-backend

# Enable debug logs (Spring Boot internal logging)
logging.level.root=INFO
debug=false

# Server port
server.port=8080

# Enable the H2 console
spring.h2.console.enabled=true

# Optional: set the path for the console
spring.h2.console.path=/h2-console

# (Optional but helpful)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Allow access from browser
spring.h2.console.settings.web-allow-others=true

# API Keys
HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
UNSPLASH_API_KEY=${UNSPLASH_API_KEY}

# Gmail SMTP (Local)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.checkserveridentity=true