package com.nelani.recipe_search_backend.notifications;

import com.nelani.recipe_search_backend.model.Recipe;
import com.nelani.recipe_search_backend.model.User;
import lombok.extern.slf4j.Slf4j;
import org.springframework.mail.javamail.JavaMailSender;
import jakarta.mail.internet.MimeMessage;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.stream.Collectors;

@Slf4j
@Service
public class EmailService {

    private final String logo = "https://ai-recipe-generator-5rbk.onrender.com/images/logo.png";
    private final JavaMailSender mailSender;

    public EmailService(JavaMailSender mailSender) {
        this.mailSender = mailSender;
    }

    @Async("emailTaskExecutor")
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    private void sendEmail(String toEmail, String subject, String htmlContent) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");
            helper.setTo(toEmail);
            helper.setSubject(subject);
            helper.setText(htmlContent, true);

            mailSender.send(message);
        } catch (Exception e) {
            log.error("Failed to send email to {} with subject '{}'", toEmail, subject, e);
        }
    }

    public void sendRecipeEmail(String email, Recipe recipe) {
        String subject = "AI Recipe Generator - " + recipe.getName();

        // Ingredients with quantity
        String ingredientsHtml = recipe.getIngredients().stream()
                .map(i -> "<li>" + i.getQuantity() + " " + i.getName() + "</li>")
                .collect(Collectors.joining());

        // Steps with estimated time
        String stepsHtml = recipe.getSteps().stream()
                .map(s -> "<li>" + s.getDescription() + " (Estimated: " + s.getEstimatedMinutes()
                        + " min)</li>")
                .collect(Collectors.joining());

        String htmlContent = "<!DOCTYPE html>"
                + "<html lang='en'>"
                + "  <head>"
                + "    <meta charset='UTF-8' />"
                + "    <meta name='viewport' content='width=device-width, initial-scale=1.0' />"
                + "    <title>AI Recipe Generator</title>"
                + "  </head>"
                + "  <body style='font-family: Arial, sans-serif; color: #333; background: #f9f9f9; margin: 0; padding: 0;'>"
                + "    <div style='max-width: 500px; width: 100%; margin: auto; background: #fff'>"
                + "      <div style='padding: 1px 20px 0 20px'>"
                + "        <h2 style='margin: 20px 0'>AI Recipe Generator</h2>"
                + "      </div>"
                + "      <div style='text-align:center;'>"
                + "        <img src='" + logo + "' alt='AI Recipe Generator Logo' "
                + "             style='width:100%;height:auto;display:block;margin-bottom:20px;'/>"
                + "      </div>"
                + "      <div style='padding: 0 20px 40px'>"
                + "        <h2 style='color: #2e86c1; margin: 40px 0 20px 0'>Hi there,</h2>"
                + "        <p style='line-height: 1.6'>"
                + "          Your custom recipe <strong>" + recipe.getName()
                + "</strong> has been generated by AI!"
                + "        </p>"
                + "        <p><strong>Meal Type:</strong> " + recipe.getMealType() + "</p>"
                + "        <p><strong>Cook Time:</strong> " + recipe.getCookTimeMinutes()
                + " minutes</p>"
                + "        <h3 style='margin-top:30px; color:#2e86c1;'>Ingredients:</h3>"
                + "        <ul style='line-height:1.6;'>" + ingredientsHtml + "</ul>"
                + "        <h3 style='margin-top:30px; color:#2e86c1;'>Steps:</h3>"
                + "        <ol style='line-height:1.6;'>" + stepsHtml + "</ol>"
                + "        <hr style='margin: 30px 0; border: none; border-top: 1px solid #ccc' />"
                + "        <p style='font-size: 13px; color: #666; text-align: center'>"
                + "          Need help? Visit our"
                + "          <a href='#' style='color: #2e86c1; text-decoration: none'>Help Center</a>"
                + "          or reply to this email."
                + "        </p>"
                + "        <p style='font-size: 12px; color: #999; text-align: center; margin-top: 15px;'>"
                + "          AI Recipe Generator – Where every dish is unique."
                + "        </p>"
                + "      </div>"
                + "    </div>"
                + "  </body>"
                + "</html>";

        // Email the recipe to the provided email
        sendEmail(email, subject, htmlContent);
    }

    public void sendPasswordResetEmail(String email, String token) {
        String subject = "AI Recipe Generator - Verification code";

        String htmlContent = "<!DOCTYPE html>"
                + "<html lang='en'>"
                + "  <head>"
                + "    <meta charset='UTF-8' />"
                + "    <meta name='viewport' content='width=device-width, initial-scale=1.0' />"
                + "    <title>Password Reset</title>"
                + "  </head>"
                + "  <body style='font-family: Arial, sans-serif; color: #333; background: #f9f9f9; margin: 0; padding: 0;'>"
                + "    <div style='max-width: 500px; width: 100%; margin: auto; background: #fff; border-radius: 10px; overflow: hidden;'>"
                + "      <div style='text-align: center; padding: 20px; background: #2e86c1; color: white;'>"
                + "        <h2 style='margin: 0;'>AI Recipe Generator</h2>"
                + "      </div>"
                + "      <div style='text-align:center; padding: 20px;'>"
                + "        <img src='" + logo + "' alt='AI Recipe Generator Logo' "
                + "             style='width: 120px; height: auto; margin-bottom: 20px;'/>"
                + "      </div>"
                + "      <div style='padding: 0 20px 40px 20px;'>"
                + "        <h3 style='color: #2e86c1;'>Reset Your Password</h3>"
                + "        <p style='line-height: 1.6;'>We received a request to reset your password for <strong>AI Recipe Generator</strong>. "
                + "        Use the code below to set a new password:</p>"
                + "        <div style='text-align: center; margin: 30px 0;'>"
                + "          <p style='font-size: 26px; font-weight: bold; color: #2e86c1; letter-spacing: 3px;'>"
                + "            " + token
                + "          </p>"
                + "        </div>"
                + "        <p style='line-height: 1.6;'>Enter this code in the app or website to reset your password. "
                + "        This code will expire in 30 minutes.</p>"
                + "        <hr style='margin: 30px 0; border: none; border-top: 1px solid #ccc' />"
                + "        <p style='font-size: 13px; color: #666; text-align: center;'>If you did not request a password reset, you can safely ignore this email.</p>"
                + "        <p style='font-size: 12px; color: #999; text-align: center; margin-top: 15px;'>© "
                + "            " + java.time.Year.now().getValue() + " AI Recipe Generator – All rights reserved.</p>"
                + "      </div>"
                + "    </div>"
                + "  </body>"
                + "</html>";

        // Email the validation token to the provided email
        sendEmail(email, subject, htmlContent);
    }

    public void sendAccountVerificationEmail(String email, String token) {
        String subject = "AI Recipe Generator - Verification code";

        String htmlContent = "<!DOCTYPE html>"
                + "<html lang='en'>"
                + "  <head>"
                + "    <meta charset='UTF-8' />"
                + "    <meta name='viewport' content='width=device-width, initial-scale=1.0' />"
                + "    <title>Email Verification</title>"
                + "  </head>"
                + "  <body style='font-family: Arial, sans-serif; color: #333; background: #f9f9f9; margin: 0; padding: 0;'>"
                + "    <div style='max-width: 500px; width: 100%; margin: auto; background: #fff; border-radius: 10px; overflow: hidden;'>"
                + "      <div style='text-align: center; padding: 20px; background: #2e86c1; color: white;'>"
                + "        <h2 style='margin: 0;'>AI Recipe Generator</h2>"
                + "      </div>"
                + "      <div style='text-align:center; padding: 20px;'>"
                + "        <img src='" + logo + "' alt='AI Recipe Generator Logo' "
                + "             style='width: 120px; height: auto; margin-bottom: 20px;'/>"
                + "      </div>"
                + "      <div style='padding: 0 20px 40px 20px;'>"
                + "        <h3 style='color: #2e86c1;'>Verify Your Email Address</h3>"
                + "        <p style='line-height: 1.6;'>Thank you for signing up for <strong>AI Recipe Generator</strong>! "
                + "        To complete your registration, please verify your email address using the code below:</p>"
                + "        <div style='text-align: center; margin: 30px 0;'>"
                + "          <p style='font-size: 26px; font-weight: bold; color: #2e86c1; letter-spacing: 3px;'>"
                + "            " + token
                + "          </p>"
                + "        </div>"
                + "        <p style='line-height: 1.6;'>Enter this verification code in the app or website to activate your account.</p>"
                + "        <hr style='margin: 30px 0; border: none; border-top: 1px solid #ccc' />"
                + "        <p style='font-size: 13px; color: #666; text-align: center;'>Didn’t create an account? Please ignore this email.</p>"
                + "        <p style='font-size: 12px; color: #999; text-align: center; margin-top: 15px;'>© "
                + "            " + java.time.Year.now().getValue() + " AI Recipe Generator – All rights reserved.</p>"
                + "      </div>"
                + "    </div>"
                + "  </body>"
                + "</html>";

        // Email the validation token to the provided email
        sendEmail(email, subject, htmlContent);
    }

    public void sendEmailChangeVerificationEmail(String newEmail, String token) {
        String subject = "AI Recipe Generator - Confirm Your New Email";

        String htmlContent = "<!DOCTYPE html>"
                + "<html lang='en'>"
                + "  <head>"
                + "    <meta charset='UTF-8' />"
                + "    <meta name='viewport' content='width=device-width, initial-scale=1.0' />"
                + "    <title>Email Change Verification</title>"
                + "  </head>"
                + "  <body style='font-family: Arial, sans-serif; color: #333; background: #f9f9f9; margin: 0; padding: 0;'>"
                + "    <div style='max-width: 500px; width: 100%; margin: auto; background: #fff; border-radius: 10px; overflow: hidden;'>"
                + "      <div style='text-align: center; padding: 20px; background: #2e86c1; color: white;'>"
                + "        <h2 style='margin: 0;'>AI Recipe Generator</h2>"
                + "      </div>"
                + "      <div style='text-align:center; padding: 20px;'>"
                + "        <img src='" + logo + "' alt='AI Recipe Generator Logo' "
                + "             style='width: 120px; height: auto; margin-bottom: 20px;'/>"
                + "      </div>"
                + "      <div style='padding: 0 20px 40px 20px;'>"
                + "        <h3 style='color: #2e86c1;'>Verify Your New Email Address</h3>"
                + "        <p style='line-height: 1.6;'>You recently requested to update your email address for your "
                + "        <strong>AI Recipe Generator</strong> account. To confirm this change, please enter the code below:</p>"
                + "        <div style='text-align: center; margin: 30px 0;'>"
                + "          <p style='font-size: 26px; font-weight: bold; color: #2e86c1; letter-spacing: 3px;'>"
                + "            " + token
                + "          </p>"
                + "        </div>"
                + "        <p style='line-height: 1.6;'>Enter this verification code in the app or website to complete your email update.</p>"
                + "        <hr style='margin: 30px 0; border: none; border-top: 1px solid #ccc' />"
                + "        <p style='font-size: 13px; color: #666; text-align: center;'>Didn’t request an email change? Please ignore this email.</p>"
                + "        <p style='font-size: 12px; color: #999; text-align: center; margin-top: 15px;'>© "
                + "            " + java.time.Year.now().getValue() + " AI Recipe Generator – All rights reserved.</p>"
                + "      </div>"
                + "    </div>"
                + "  </body>"
                + "</html>";

        // Send confirmation token to the new email
        sendEmail(newEmail, subject, htmlContent);
    }

    public void sendWelcomeEmail(String email, String fullName) {
        String subject = "Welcome to AI Recipe Generator";

        String htmlContent = "<!DOCTYPE html>"
                + "<html lang='en'>"
                + "  <head>"
                + "    <meta charset='UTF-8' />"
                + "    <meta name='viewport' content='width=device-width, initial-scale=1.0' />"
                + "    <title>Welcome Email</title>"
                + "  </head>"
                + "  <body style='font-family: Arial, sans-serif; color: #333; background: #f9f9f9; margin: 0; padding: 0;'>"
                + "    <div style='max-width: 500px; width: 100%; margin: auto; background: #fff; border-radius: 10px; overflow: hidden;'>"
                + "      <div style='text-align: center; padding: 20px; background: #2e86c1; color: white;'>"
                + "        <h2 style='margin: 0;'>AI Recipe Generator</h2>"
                + "      </div>"
                + "      <div style='text-align:center; padding: 20px;'>"
                + "        <img src='" + logo + "' alt='AI Recipe Generator Logo' "
                + "             style='width: 120px; height: auto; margin-bottom: 20px;'/>"
                + "      </div>"
                + "      <div style='padding: 0 20px 40px 20px;'>"
                + "        <h3 style='color: #2e86c1;'>Welcome to the AI-powered cooking experience, " + fullName
                + "!</h3>"
                + "        <p style='line-height: 1.6;'>We're thrilled to have you on board at <strong>AI Recipe Generator</strong>! "
                + "        Get ready to explore personalized recipes, generate meal ideas with AI, and discover new flavors effortlessly.</p>"
                + "        <div style='text-align: center; margin: 30px 0;'>"
                + "          <a href='https://ai-recipe-generator-5rbk.onrender.com/swagger-ui/index.html' "
                + "             style='background: #2e86c1; color: #fff; padding: 12px 25px; text-decoration: none; "
                + "                    border-radius: 5px; font-size: 16px; display: inline-block;'>"
                + "             Start Cooking Now"
                + "          </a>"
                + "        </div>"
                + "        <p style='line-height: 1.6;'>If you have any questions, feel free to reach out – we’re always here to help you cook smarter.</p>"
                + "        <hr style='margin: 30px 0; border: none; border-top: 1px solid #ccc' />"
                + "        <p style='font-size: 13px; color: #666; text-align: center;'>You’re receiving this email because you created an account with us.</p>"
                + "        <p style='font-size: 12px; color: #999; text-align: center; margin-top: 15px;'>© "
                + java.time.Year.now().getValue() + " AI Recipe Generator – All rights reserved.</p>"
                + "      </div>"
                + "    </div>"
                + "  </body>"
                + "</html>";

        sendEmail(email, subject, htmlContent);
    }

    public void sendAccountDeletionEmail(String email, String fullName) {
        String subject = "Your AI Recipe Generator Account Has Been Deleted";

        String htmlContent = "<!DOCTYPE html>"
                + "<html lang='en'>"
                + "  <head>"
                + "    <meta charset='UTF-8' />"
                + "    <meta name='viewport' content='width=device-width, initial-scale=1.0' />"
                + "    <title>Account Deletion Confirmation</title>"
                + "  </head>"
                + "  <body style='font-family: Arial, sans-serif; color: #333; background: #f9f9f9; margin: 0; padding: 0;'>"
                + "    <div style='max-width: 500px; width: 100%; margin: auto; background: #fff; border-radius: 10px; overflow: hidden;'>"
                + "      <div style='text-align: center; padding: 20px; background: #2e86c1; color: white;'>"
                + "        <h2 style='margin: 0;'>AI Recipe Generator</h2>"
                + "      </div>"
                + "      <div style='text-align:center; padding: 20px;'>"
                + "        <img src='" + logo + "' alt='AI Recipe Generator Logo' "
                + "             style='width: 120px; height: auto; margin-bottom: 20px;'/>"
                + "      </div>"
                + "      <div style='padding: 0 20px 40px 20px;'>"
                + "        <h3 style='color: #2e86c1;'>Goodbye for now, " + fullName + "</h3>"
                + "        <p style='line-height: 1.6;'>We wanted to let you know that your <strong>AI Recipe Generator</strong> "
                + "        account has been successfully deleted as per your request.</p>"
                + "        <p style='line-height: 1.6;'>All associated data, including saved recipes and preferences, "
                + "        has been permanently removed and cannot be recovered.</p>"
                + "        <p style='line-height: 1.6;'>We're sad to see you go, but we truly appreciate the time you spent with us. "
                + "        If you ever decide to return, we'll be here to help you cook smarter with AI once again. 🍽️🤖</p>"
                + "        <hr style='margin: 30px 0; border: none; border-top: 1px solid #ccc' />"
                + "        <p style='font-size: 13px; color: #666; text-align: center;'>If this was a mistake or you didn’t request this change, "
                + "        please contact our support immediately.</p>"
                + "        <p style='font-size: 12px; color: #999; text-align: center; margin-top: 15px;'>© "
                + java.time.Year.now().getValue() + " AI Recipe Generator – All rights reserved.</p>"
                + "      </div>"
                + "    </div>"
                + "  </body>"
                + "</html>";

        sendEmail(email, subject, htmlContent);
    }

}
